### ISSUE TITLE
Create static site for app

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#105]
* style HTML from README
* deploy (gh pages? S3?)

@ejfox can you add your mocks here?

**Comment by ejfox** [comment]
![dataproofer-site-mock](https://cloud.githubusercontent.com/assets/530073/14508688/b1f2d182-0196-11e6-92c6-1248416880b4.png)

**Comment by ejfox** [comment]
First iteration: http://dataproofer.github.io/Dataproofer/

![screenshot 2016-04-15 13 28 29](https://cloud.githubusercontent.com/assets/530073/14569640/f595c76e-030d-11e6-94d3-3841327581a4.png)
