### ISSUE TITLE
Replace checkboxes with result icons (check, x, or warning triangle) on step 3

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#107]
When "run checks" is pressed and you are moved on to step 3, the checkboxes should be replaced with the results of the test, or at the very least removed

When you click the "Select checks" button the icons should be replaced with the checkboxes again

**Comment by geraldarthur** [comment]
pushed some logic to help do this

![screen_shot_2016-04-14_at_5_23_17_pm](https://cloud.githubusercontent.com/assets/1578563/14547853/a73749c8-0266-11e6-980c-bade3f4069ee.png)

**Comment by ejfox** [comment]
@geraldarthur killin it yet again 🔥
