### ISSUE TITLE
Don't show conclusion if test passes

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#108]
For example, this dataset isn't missing any rows, and shows at green, but when you hover over the info you get a conclusion that makes it seem like you have a problem

<img width="976" alt="screenshot 2016-04-13 22 35 34" src="https://cloud.githubusercontent.com/assets/530073/14515442/24e4bac6-01c8-11e6-876f-ebf809f53564.png">

**Comment by geraldarthur** [comment]
fixed with 1e0c537322f095e49f4810b8673c429897f1e2c5

![screen shot 2016-04-13 at 10 01 14 pm](https://cloud.githubusercontent.com/assets/1578563/14517533/596493e8-01c3-11e6-9228-c77df66011bf.png)
