### ISSUE TITLE
Confused about empty cells in Excel files

### ISSUE THREAD

**Issue by Fil** [dataproofer/Dataproofer#111]
When I uploaded this xls file the empty cells were ignored / confused. It does not happens if I export the file to csv before.

[test empty.xlsx](https://github.com/dataproofer/Dataproofer/files/218941/test.empty.xlsx)
[test empty.csv](https://github.com/dataproofer/Dataproofer/files/218943/test.empty.csv.txt)

![capture d ecran 2016-04-14 12 50 52](https://cloud.githubusercontent.com/assets/7001/14525918/414b38ac-0240-11e6-981e-5b516d9234ca.png)

**Comment by geraldarthur** [comment]
Nice catch @Fil! I've patched this by converting the Excel file to a CSV string so it doesn't accidentally strip out empty cells & columns edb635aac3580759401754468adebdfc03e33710.

![screen shot 2016-04-14 at 11 47 07 am](https://cloud.githubusercontent.com/assets/1578563/14539946/a7e84f54-0237-11e6-8c23-e97874669b6d.png)

Excel parsing can be a bit of a rabbit hole, but we'll be making more improvements after we launch the prototype. Hope this helps and thanks again for letting us know!
