### ISSUE TITLE
Recommend adding more information about what Dataproofer is to main website.

### ISSUE THREAD

**Issue by melodykramer** [dataproofer/Dataproofer#114]
The README has a great description! Is there a way to put what's below above the video? This will also make the site more accessible. 👍 Nice work @geraldarthur! 

Every day, more and more data is created. Journalists, analysts, and data visualizers turn that data into stories and insights.

But before you can make use of any data, you need to know if it’s reliable. Is it weird? Is it clean? Can I use it to write or make a viz?

This used to be a long manual process, using valuable time and introducing the possibility for human error. People can’t always spot every mistake every time, no matter how hard they try.

Data proofer is built to automate this process of checking a dataset for errors or potential mistakes.

**Comment by ejfox** [comment]
Honored that you took a look @melodykramer, and thank you! Have just updated the site to reflect this. Let me know if that's what you were thinking.

**Comment by melodykramer** [comment]
YES, excellent work @ejfox - makes it much easier for folks to understand what the tool is and does. 👍
