### ISSUE TITLE
Resizing window

### ISSUE THREAD

**Issue by georules** [dataproofer/Dataproofer#119]
### Summary

UI - Resizing window doesn't fit content to new pane
### Steps to reproduce

Resize the window
### Expected behavior

Pane does not repaint to fill the new dimensions
### Relevant logs and/or screenshots

(censored emails)
![screen shot 2016-04-22 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/775628/14754394/22616fb4-08a9-11e6-88f0-876b92a8e36d.png)
![screen shot 2016-04-22 at 4 39 35 pm](https://cloud.githubusercontent.com/assets/775628/14754395/2468eecc-08a9-11e6-8926-6dedc0493a07.png)
### Possible fixes?

A view>reload works, but then you have to reload your file.
### Related issues/pull requests?

I did not notice any issues related to resizing

**Comment by ejfox** [comment]
Cheers!

@geraldarthur I think we might want to debounce just re-rendering the grid on window.resize?

**Comment by geraldarthur** [comment]
hey! i missed this one @ejfox @georules. my apologies! will be working on a fix for this in `v1.1`. will push another update to this ticket when this is fixed and can ping you again once we've got this available for download

**Comment by ejfox** [comment]
So it handles getting larger fine, but resizing so it is smaller breaks it (the left sidebar becomes hidden)

<img width="612" alt="Screenshot 2019-07-10 13 01 52" src="https://user-images.githubusercontent.com/530073/60989010-e9dfae00-a312-11e9-8b6e-66bd8d19a566.png">
<img width="946" alt="Screenshot 2019-07-10 13 01 56" src="https://user-images.githubusercontent.com/530073/60989011-e9dfae00-a312-11e9-8421-8e20105da21e.png">
<img width="1261" alt="Screenshot 2019-07-10 13 02 02" src="https://user-images.githubusercontent.com/530073/60989012-ea784480-a312-11e9-9c14-f41c50c4ba78.png">
