### ISSUE TITLE
Dataproofer should not depend on libnotify

### ISSUE THREAD

**Issue by mehmetaergun** [dataproofer/Dataproofer#124]
### Summary

As an automated data cleaning tool, this should not need to depend on libnotify being installed.
### Steps to reproduce
1. create virtual machine (debian 8, base installation, no X)
2. install basic X and X window manager tools (dwm)
3. launch Dataproofer
4. crashes. "error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory"
### Expected behavior

Should launch 

Thanks :)

**Comment by ejfox** [comment]
@mehmetaergun Sorry for the delay on this. 

So this looks like it is a dependency of electron in general and not dataproofer specifically. See [Electron prerequisites](https://github.com/electron/electron/blob/master/docs/development/build-instructions-linux.md#prerequisites) which says on Ubuntu you'd wanna do - note `libnotify-dev`.

```bash
$ sudo apt-get install build-essential clang libdbus-1-dev libgtk-3-dev \
                       libnotify-dev libgnome-keyring-dev libgconf2-dev \
                       libasound2-dev libcap-dev libcups2-dev libxtst-dev \
                       libxss1 libnss3-dev gcc-multilib g++-multilib curl \
                       gperf bison python-dbusmock openjdk-8-jre
```

I think that users on linux can be expected to be much more comfortable with the command line, and if you're concerned about extra dependencies, the [CLI dataproofer published on npm](https://www.npmjs.com/package/dataproofer) is probably a better fit for our more advanced users. 

@mehmetaergun Can you let me know if you are able to install dataproofer using npm and run it?

If so, can we close this ticket?

**Comment by mehmetaergun** [comment]
Thanks for the update. I do not have a strong opinion on this other than
libnotify not being a library needed for core functionality. Please feel
free to close the ticket as you see fit. Thanks again.

**Comment by ejfox** [comment]
Okay cool, I think we are in agreement then. I think of the electron GUI as a way to get started or onboard less-technical users (who I think we can assume won't be running Debian). Debian users should use the CLI as it has all the features and is much lighter in terms of dependencies. 

Thank you for your quick response! Gonna close this for now.
