### ISSUE TITLE
Create JSON report export 

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#130]
Great idea from @fil here: https://github.com/dataproofer/Dataproofer/issues/64#issuecomment-218728978 

When using Dataproofer in a CLI context, it is most useful in a workflow if the results are given in a way that can be automated or used by other applications.

One way to approach this is to create a JSON template that can be exported that contains the results of the tests that ran.

The other is to return extremely simple, repeatable values depending on command flags passed to the dataproofer CLI. For example "dataproofer --boolean-report file.csv" might simply return "1" or "0" depending on whether all the tests pass or fail.

**Comment by geraldarthur** [comment]
Added to master with 20125b67ed3e395522e10c6869d1e8618c1d96a6 in the CLI tool. Documentation has been updated with pseudo-code [with a new section](https://github.com/dataproofer/Dataproofer#getting-started-command-line) to help new users output JSON reports.
