### ISSUE TITLE
"Error: No feed was returned"

### ISSUE THREAD

**Issue by charlex** [dataproofer/Dataproofer#137]
### Summary

When importing gsheet, I get "`Error: No feed was returned`"

Mac 10.11.6 (15G31)
Electron app
Both in downloaded .app and in dev environment
### Steps to reproduce

Use `https://docs.google.com/spreadsheets/d/1zeitKHGaHjjTYjr4XvQNxK6Ug7rVSBkXLhdDEgm5yZg/edit#gid=2014102820`
### Expected behavior

Supposed to load a gsheet
### Relevant logs and/or screenshots

This is the console log from handleGsheetsError after printing out `err`
`controller.js:620 Error: No feed was returned
    at /Users/cbodkin/code/dataproofer/electron/node_modules/gsheets/index.js:22:43`
### Possible fixes?

Probably want to catch this error from the gsheets dependency and return a more human readable message. Or patch gsheets.
### Related issues/pull requests?

N/A

**Comment by charlex** [comment]
Just filed a ticket with gsheets. https://github.com/interactivethings/gsheets/issues/4

**Comment by herrstucki** [comment]
@charlex I tested your spreadsheet this with the following code:

```js
gsheets.getWorksheetById('1zeitKHGaHjjTYjr4XvQNxK6Ug7rVSBkXLhdDEgm5yZg', '2014102820', function(err, res) {
  if (err) return console.error(err);
  console.log(res)
});
```
and I get this error:

```
Error: Google Spreadsheets responded with HTTP error 302. Are you sure the spreadsheet exists and is published?"
```

So the problem seems to be that you didn't publish your spreadsheet. I don't really know where the "No feed was returned" message comes from though.
