### ISSUE TITLE
Questions / Suggestions for extending use outside journalism community

### ISSUE THREAD

**Issue by b44p** [dataproofer/Dataproofer#141]
Hey there - fellow Knight grantee here and working on deploying this for data hygiene exercises in other domains - mainly municipal contexts.

**There are suggestions for the Desktop App**

**1. Can I export proof results as an editable document or new git project?**
I am thinking `dataproofer FOO.FILE -o PDF/DOC/TXT` to generate the results of some basic tests into a document that. Alternatively `dataproofer FOO.FILE -o GIT` to auto generate a full on GIT project around that file and each failed Proof test translates into an issue on that GIT project.

**2. Pre-defining datatypes on columns**
Ability to assign some basic rules such as this numeric column is categorical and not continuous data so that proofer skips numeric tests.
Explicitly defining columns as GEO to trigger geo-tests.

**Comment by geraldarthur** [comment]
Hey @b44p! You can export Dataproofer's results using the command line tool. Here's a link with [more information](https://www.npmjs.com/package/dataproofer).

You can also use it to specify tests or sets of tests on the columns you'd like to run them on. Hope this helps, and feel free to email me dataproofer at dataproofer.org. I appreciate the suggestions! Going to close this issue, but I'm please file more in the future as needed and don't hesitate to reach out if there's anything else I can do. -Gerald

**Comment by b44p** [comment]
Thanks!
