### ISSUE TITLE
Incorrect d3 functions

### ISSUE THREAD

**Issue by lexieheinle** [dataproofer/Dataproofer#142]
### Summary
I ran into some TypeErrors due to using the wrong names for d3 functions, such as d3.scale.threshold() and d3.drag. I'm on a Mac, and the dataset had 2,890 rows.
### Steps to reproduce
After selecting my csv, the program stayed on the pick test screen due to hitting the TypeErrors, and there was no indicator that something was wrong.
### Possible fixes?
I was able to fix the d3.scale.threshold() error by changing [electron/renderer.js](https://github.com/dataproofer/Dataproofer/blob/master/electron/js/renderer.js#L139) to use the correct function name. I can submit a pull request as well.

**Comment by ejfox** [comment]
@enjalot @geraldarthur Is this an issue with D3 v3 vs v4 getting introduced somehow?

**Comment by enjalot** [comment]
Yeah, this is definitely a v3 vs v4 issue, but I'm not sure how d3.v4 got introduced. are we not specifying the version in the package.json?

**Comment by ejfox** [comment]
Looks like it got accidentally bumped up to 4 here: https://github.com/dataproofer/Dataproofer/commit/6f606da08a5a4fd9c73a3c2417a1ff8e93bda438#diff-59f51de4945d3a9a80a254062862997b

Just pushed it back to V3 

/cc @geraldarthur
