### ISSUE TITLE
Correctly sort columns with dollars or percents

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#41]
### Summary
Sorting on dollars or percents returns an incorrectly sorted column. Mac OS X v10.11.3
### Steps to reproduce
Loaded sample dataset `sf-police-salaries.csv`, ran stats-suite, then tried to sort the salaries by clicking on the column header's name
### Expected behavior
Column should sort from $0 to $999,999 regardless of formatting
### Sreenshots/Logs
![screen shot 2016-03-22 at 6 19 19 pm](https://cloud.githubusercontent.com/assets/1578563/13972929/a7f39b28-f05a-11e5-8b19-cc59d5595f48.png)
### Possible fixes?
There's a couple of different [format options](https://docs.handsontable.com/0.24.1/Options.html#format) we can pass to the grid so it knows how to properly sort a column. This will require additional formatting checks added to [dataproofertest-js/util.js](https://github.com/dataproofer/dataproofertest-js/blob/master/util.js) in order to help automatically specify the columns type.
- [ ] add util function to check for USD. should return true/false
- [ ] add util function to check for percents. should return true/false
- [ ] pass an array of objects detailing format info for each column to the `columns` option. See `new Handsontable` in [renderer.js](https://github.com/dataproofer/Dataproofer/blob/master/electron/js/renderer.js)

**Comment by ejfox** [comment]
Disabled sorting in the grid for other reasons, but it happens to fix this also. nice.
