### ISSUE TITLE
Redraw CSV minimap canvas element after column sort

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#42]
### Summary
Sorting columns breaks CSV minimap/fingerprint visualization.
### Steps to reproduce
Loaded `sf-police-salaries.csv`, clicked on column header `Base`
### Expected behavior
Minimap still highlighted cells that had since been re-sorted. Minimaps will need to update when cells are sorted
### Relevant logs and/or screenshots
![sorting-fingerprint-bug](https://cloud.githubusercontent.com/assets/1578563/13973236/1b610e76-f05e-11e5-8cbb-ffcac64b5685.gif)
### Possible fixes?
Clear and redraw canvas after HandsOnTable fires [afterColumnSort](https://docs.handsontable.com/0.24.1/Hooks.html#event:afterColumnSort) event in [renderer.js](https://github.com/dataproofer/Dataproofer/blob/master/electron/js/renderer.js)

**Comment by ejfox** [comment]
We've removed column sorting so this isn't an issue anymore
