### ISSUE TITLE
Highlight any row with an error with a red row number

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#48]
### Summary
It would be nice to scan the spreadsheet view on the right and see where the errors are

![screenshot 2016-03-25 15 00 43](https://cloud.githubusercontent.com/assets/530073/14051691/4addbd7c-f29b-11e5-84ab-4b676ff12aae.png)

**Comment by geraldarthur** [comment]
Requires a day or less to add some logic here: [./electron/js/renderer.js#L50](https://github.com/dataproofer/Dataproofer/blob/master/electron/js/renderer.js#L50 ). The logic should check for any truthy value in the row by looping over highlightCells' column heads. If it finds a truthy value, select that row's header cell, `span.rowHeader`, with `d3.select()` and then color it red.
