### ISSUE TITLE
Test: check for character encoding issues

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#5]
*Please read [how to create a new test](https://github.com/dataproofer/Dataproofer#creating-a-new-test) if you're interested in writing this test.*

And on a related note, do we force encode files to UTF-8?

**Comment by enjalot** [comment]
I was trying to turn this into a tsv after i deleted the header and ran it through dataproofer which did alert me to a weird corrupt character (turned out there were more that it didn't catch):
https://www.census.gov/popest/data/counties/asrh/1990s/tables/co-99-09/CO-99-9-13.txt
