### ISSUE TITLE
Check to restrict filetypes permitted

### ISSUE THREAD

**Issue by xaranke** [dataproofer/Dataproofer#58]
### Summary
I managed to import an HTML document into Dataproofer which it then interpreted as a spreadsheet and spat out irrelevant stats. Dataset was the HTML of the front page of Hacker News
[(attached)](https://github.com/dataproofer/Dataproofer/files/192615/Hacker.News.html.zip). I did this on OS X 10.11.4 but OS/Version shouldn't really matter.
### Steps to reproduce
Import attached XML document into Dataproofer.
### Expected behavior
Maybe tell me that the data type is unsupported or at least don't run stats on what is clearly not a valid dataset.
### Relevant logs and/or screenshots
<img width="1280" alt="screen shot 2016-03-28 at 6 16 53 pm" src="https://cloud.githubusercontent.com/assets/1210776/14093140/55a5ff1c-f511-11e5-8f5a-a03038f7b007.png">
### Possible fixes?
Be especially suspicious of a dataset with a single column. Maybe pop up a warning asking the user if they are sure that this is what they want to do.
### Related issues/pull requests?
None that I am aware of. I doubt that this was introduced from a pull request -- just seems to be an edge case that may not have been handled.

UPDATE: This seems to work on binary data as well, I imported images and zip files successfully into Dataproofer which should not happen.

Thanks!

**Comment by ejfox** [comment]
@xaranke Thank you so much for our first issue! 

You're totally right, this is an edge case we didn't really think of, will definitely patch ASAP this week. 

Please let us know anything else you find, we really appreciate your time and feedback. :+1:

**Comment by xaranke** [comment]
Happy to help! :smiley: 

Another thing I've discussed with @enjalot over Twitter is removing the Chrome Developer Console from the final product :wink:. Just leaving this in a comment since I'm feeling lazy to create a new issue for this tiny bug.

**Comment by enjalot** [comment]
the latest build removed the dev console by default (and should also be a smaller file size).
