### ISSUE TITLE
Read in Excel file data

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#63]
Currently the app handles data from a CSV file or a Google Spreadsheet tab. We'd need to add this functionality into the logic in `src/` and some UI into `electron/`. Dataproofer reads spreadsheets in as an array of row objects, so we'll have to convert it if it comes in as an array of row arrays.

## Possible Fix
[Node XLSX](https://www.npmjs.com/package/node-xlsx)

**Comment by ejfox** [comment]
Random idea... Could we maybe link to Tabula if a user drops in a PDF?

**Comment by geraldarthur** [comment]
#66 has been added. i'm planning on closing this branch over the weekend. gonna get some rest and then qa the branch before our next sprint. next actions all on me: review the PR, merge, then we can close this and #58.

**Comment by geraldarthur** [comment]
#65 fixes this. Commenting and closing this out unless anyone runs into any errors.
