### ISSUE TITLE
Add an "all checks passed!" state

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#76]
### Summary
It looks strange to have nothing in the step-3-results area

Would be nice to have a happy dataproofer robot with his thumb up or something

I really like this one, for example: 
![image](https://cloud.githubusercontent.com/assets/530073/14335286/f2b2fbee-fc0e-11e5-8c9b-fbbdf2f79b32.png)

**Comment by ejfox** [comment]
Example of how it is now: 

<img width="1292" alt="screenshot 2016-04-06 15 45 53" src="https://cloud.githubusercontent.com/assets/530073/14335309/11faac5e-fc0f-11e5-8146-1dcf9b61f1e9.png">

**Comment by ejfox** [comment]
Gonna talk to Rob and see if he can work his magic

**Comment by ejfox** [comment]
![](https://files.slack.com/files-pri/T024WGGK5-F0ZUK8MUK/screen_shot_2016-04-12_at_10.28.59_am.png)
[2016_data_proofer_approved_screen.ai.zip](https://github.com/dataproofer/Dataproofer/files/215738/2016_data_proofer_approved_screen.ai.zip)

**Comment by ejfox** [comment]
@geraldarthur @enjalot Is there logic for this yet? Like is there a spot in renderer I can plug in this HTML? Or do we need to make logic for when all tests are passed as well?

**Comment by enjalot** [comment]
There is a hook in the renderer when all tests are done running. you'd have
to loop over them to check if they all passed though.

On Tue, Apr 12, 2016 at 12:15 PM, EJ Fox <notifications@github.com> wrote:

> @geraldarthur <https://github.com/geraldarthur> @enjalot
> <https://github.com/enjalot> Is there logic for this yet? Like is there a
> spot in renderer I can plug in this HTML? Or do we need to make logic for
> when all tests are passed as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dataproofer/Dataproofer/issues/76#issuecomment-209060205>
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by ejfox** [comment]
@geraldarthur Can you make the logic that I can hook this styling into?

**Comment by geraldarthur** [comment]
Sure thing. Will do this evening

**Comment by geraldarthur** [comment]
Added `all-passed` class to `test-sets` w/ this commit 67db62d5046d4bbe2437fe42daa88494a398cb8f

**Comment by ejfox** [comment]
<img width="732" alt="screenshot 2016-04-13 00 16 52" src="https://cloud.githubusercontent.com/assets/530073/14482671/1084af34-010d-11e6-8118-f6d8314dc67f.png">
