### ISSUE TITLE
Fix build script

### ISSUE THREAD

**Issue by geraldarthur** [dataproofer/Dataproofer#83]
Builds a 600mb app right now...I don't think we're that large :stuck_out_tongue: . Is there anyway we can improve the build script so it reduces the size of the executables?

**Comment by enjalot** [comment]
ill check it out. i get 50mb builds (zipped). i think its due to linked
node modules somehow, or its including the executables its already built in
the build

**Comment by geraldarthur** [comment]
fixed with e5c2b8c
