### ISSUE TITLE
Add test results to test selection checkbox-tree

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#88]
This is a continuation of https://github.com/dataproofer/Dataproofer/issues/87

Once we have the tree-checkbox set up for test/set selection, need to enable results view and filtering in it. 

Need to add green checks for tests that have passed, and red X's for tests that have failed. Also to need to refactor the "filter" button to be "show". 

![whiteboard_img_3432_720](https://cloud.githubusercontent.com/assets/530073/14398209/6f5231c2-fdb0-11e5-8edb-e0962f552d95.jpg)

**Comment by geraldarthur** [comment]
added some logic to help with this 7938d8a

![screen_shot_2016-04-14_at_5_23_17_pm](https://cloud.githubusercontent.com/assets/1578563/14547875/c7addf32-0266-11e6-9296-8bdb0b73151e.png)

**Comment by ejfox** [comment]
Doooooneee!!!
