### ISSUE TITLE
Show test edit button on hover

### ISSUE THREAD

**Issue by ejfox** [dataproofer/Dataproofer#98]
I've temporarily hidden the edit test button

Couple of options:
- Show the edit test button on hover
- Set 'advanced user' config that shows extra options, like the edit test button
- Clearly document in the UI and documentation that shift-click lets you edit tests

**Comment by enjalot** [comment]
I vote for showing it on hover. I feel like at this stage its the main way we'd like to introduce test writers, and it would help if we want test writers to be our early adopters.

**Comment by ejfox** [comment]
@floodfish Would be curious about your thoughts here

**Comment by floodfish** [comment]
Hover works for me, especially if it is small but unambiguous
